import { useEffect } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';

import { RankBadge } from '@/components/ui/RankBadge';
import { MasteryCard, ShiftButton } from '@/components/ui/ShiftUI';
import { theme } from '@/constants/theme';
import { useGameStore } from '@/store/gameStore';

export default function HomeScreen() {
  const router = useRouter();
  const initialize = useGameStore((s) => s.initialize);
  const totalXp = useGameStore((s) => s.totalXp);
  const completedScenarioIds = useGameStore((s) => s.completedScenarioIds);
  const scenarios = useGameStore((s) => s.scenarios);
  const protocols = useGameStore((s) => s.protocols);
  const startShift = useGameStore((s) => s.startShift);
  const getProtocolMastery = useGameStore((s) => s.getProtocolMastery);

  useEffect(() => {
    initialize();
  }, [initialize]);

  const handleStartShift = () => {
    const scenarioId = startShift();
    if (scenarioId) {
      router.push(`/scenario/${scenarioId}`);
    }
  };

  const mastery = getProtocolMastery();
  const protocolSessionStats = useGameStore((s) => s.protocolSessionStats);
  const revealedMastery = mastery.filter((entry) => {
    const hasStaticCompleted = scenarios.some(
      (s) => s.protocolId === entry.protocolId && completedScenarioIds.includes(s.id)
    );
    const hasGeneratedCompleted =
      (protocolSessionStats[entry.protocolId]?.completed ?? 0) > 0;
    return hasStaticCompleted || hasGeneratedCompleted;
  });

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.hero}>
          <Text style={styles.academy}>FRANKLIN EMS ACADEMY</Text>
          <Text style={styles.title}>Medic Shift</Text>
          <Text style={styles.tagline}>
            Dispatch. Assess. Diagnose. Treat. Calls generated by chief complaint — same dispatch, hidden diagnosis changes every shift.
          </Text>
        </View>

        <RankBadge totalXp={totalXp} />

        <View style={styles.shiftCard}>
          <Text style={styles.shiftLabel}>ACTIVE SHIFT</Text>
          <Text style={styles.shiftPrompt}>
            Incoming call waiting. No chief complaint details until you respond.
          </Text>
          <ShiftButton label="START SHIFT" onPress={handleStartShift} />
        </View>

        {revealedMastery.length > 0 && (
          <View style={styles.masterySection}>
            <Text style={styles.masteryTitle}>Protocol Mastery</Text>
            {revealedMastery.map((entry) => (
              <MasteryCard
                key={entry.protocolId}
                protocolName={protocols[entry.protocolId]?.name ?? entry.protocolId}
                solved={entry.solved}
                total={entry.total}
              />
            ))}
          </View>
        )}

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            {completedScenarioIds.length} calls completed this session
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    padding: theme.spacing.lg,
    paddingBottom: theme.spacing.xl,
  },
  hero: {
    marginBottom: theme.spacing.lg,
  },
  academy: {
    color: theme.colors.emsBlue,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 2,
    marginBottom: theme.spacing.sm,
  },
  title: {
    color: theme.colors.text,
    fontSize: 32,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  tagline: {
    color: theme.colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: theme.spacing.sm,
  },
  shiftCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.lg,
  },
  shiftLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    marginBottom: theme.spacing.sm,
  },
  shiftPrompt: {
    color: theme.colors.text,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: theme.spacing.lg,
  },
  masterySection: {
    marginBottom: theme.spacing.lg,
  },
  masteryTitle: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: theme.spacing.sm,
  },
  footer: {
    alignItems: 'center',
    paddingTop: theme.spacing.md,
  },
  footerText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontFamily: 'SpaceMono',
  },
});
